### ISSUE TITLE
The script tag contains invalid JSON that cannot be parsed.

### ISSUE THREAD

**Issue by VasudevHarshal-123** [ampproject/amp.dev#3761]
Issue #3716 
All the "," were not removed.

**Comment by VasudevHarshal-123** [comment]
@matthiasrohmer Should I commit the corrections?

**Comment by robinvanopstal** [comment]
I've fixed it already, thank you !

**Comment by VasudevHarshal-123** [comment]
@robinvanopstal  Correct me if I'm wrong but I think you missed `"pageview": "https://foo.com/pixel?RANDOM",` at the starting of the page.
