### ISSUE TITLE
Pixi times out due to amp-script timing out

### ISSUE THREAD

**Issue by nainar** [ampproject/amp.dev#4879]
Tracking fix here: https://github.com/ampproject/amphtml/issues/30548

**Comment by patrickkettner** [comment]
@nainar @caroqliu @samouri 

this still is occurring, but the tracking bug is closed - is there a more up to date place to keep up with this information?

**Comment by samouri** [comment]
I think our usual protocol is to close a bug when the fix is merged instead of when it lands on stable. The [fix](https://github.com/ampproject/amphtml/pull/31258) is only in Beta right now. It should make it to stable this week. If the bug is still occurring after the fix is in stable then lets reopen the issue.

**Comment by nainar** [comment]
@patrickkettner can we confirm that this is fixed?

**Comment by nainar** [comment]
This doesn't look fixed to me (tested right now)
<img width="1182" alt="Screen Shot 2021-01-19 at 3 38 44 PM" src="https://user-images.githubusercontent.com/7919520/105107197-6b69dd80-5a6c-11eb-9aa6-432cd5ec76ce.png">

**Comment by patrickkettner** [comment]
@kristoferbaxter @samouri This is still happening today - you can replicate it on prod by searching for any url on https://amp.dev/page-experience, and then backgrounding the tab for a few minutes. 

Would this still be considered a bug? Or is this just something that pixi needs to be accounting for some how?

**Comment by samouri** [comment]
Still a bug! Sorry this has taken a bit of a backseat for me.
Will retriage and see if I can fit it into the work I'm doing on amp-script next week.
